#!/bin/bash

die() {
    printf 'ERROR: '
    echo $*
    exit 1
}
DEVICE='Amlogic-ng'
DIR_BUILD="build.HybridELEC-$DEVICE"
DIR_SYSTEM="$DIR_BUILD/system"
DIR_PART1="$DIR_BUILD/part1"
DIR_PART2="$DIR_BUILD/part2"
DIR_PARTS="$DIR_BUILD/parts"
DIR_TARGET='target'

echo 'Initializing build dir...'
for DIR in "$DIR_BUILD" "$DIR_SYSTEM" "$DIR_PART1" "$DIR_PART2" "$DIR_PARTS"; do
    rm -rf "$DIR" || die "Failed to remove existing build dir '$DIR'"
    mkdir -p "$DIR" || die "Failed to create dir '$DIR'"
done
mkdir -p "$DIR_TARGET" || die 'Failed to create target dir'

# Basic partition layout
IMAGE_PART1="$DIR_PARTS/part1.part"
IMAGE_PART2="$DIR_PARTS/part2.part"
IMAGE_DISK="$DIR_TARGET/HybridELEC-$DEVICE-CE_${HYBRID_VERSION_CE}_EE_$HYBRID_VERSION_EE.img"

echo 'Allocating disk space for image...'
truncate -s 2G "$IMAGE_PART1" || die 'Failed to allocate disk space for partition 1 (system/HYBRIDELEC)'
truncate -s 32M "$IMAGE_PART2" || die 'Failed to allocate disk space for partition 2 (storage/STORAGE)'
truncate -s 2081M "$IMAGE_DISK" || die 'Failed to allocate disk space for whole image'  # A 4M gap is leaved in case of faulty SD cards

echo 'Creating partition layout...'
parted -s "$IMAGE_DISK" mklabel MSDOS || die 'Failed to create partition table'
parted -s "$IMAGE_DISK" mkpart primary fat32 1MiB 2049MiB || die 'Failed to create partition in partition table'
parted -s "$IMAGE_DISK" mkpart primary ext4 2049MiB 100% || die 'Failed to create partition in partition table'

# Storage partition
echo 'Populating part2...'
touch "$DIR_PART2/.please_resize_me" || die 'Failed to create fs-resize mark'
mkdir -p "$DIR_PART2/"{core,emu}"elec" || die 'Failed to create ce and ee storage dir'
fakeroot mkfs.ext4 -m 0 -L 'DATA' -d "$DIR_PART2" "$IMAGE_PART2" || die 'Failed to create image for part2'

# System partition
echo 'Populating part1...'
mkfs.vfat -F 32 -n 'HYBRIDELEC' "$IMAGE_PART1" || die 'Failed to create fat32 on system partition'

echo 'Generating startup scripts...'
# System content
mkimage -A arm64 -O linux -T script -C none -d 'bootloader/aml_autoscript.sh' "$DIR_PART1/aml_autoscript" || die "Failed to generate aml_autoscript"
mkimage -A arm64 -O linux -T script -C none -d 'bootloader/Generic_cfgload.sh' "$DIR_PART1/cfgload" || die "Failed to generate cfgload"

DIR_BUILD_CE="distros/CoreELEC/build.CoreELEC-$DEVICE.arm-20"
DIR_BUILD_EE="distros/EmuELEC/build.EmuELEC-$DEVICE.aarch64-4"

DIR_DTB_SUFFIX='image/system/usr/share/bootloader/device_trees'
DIR_DTB_CE="$DIR_BUILD_CE/$DIR_DTB_SUFFIX"
DIR_DTB_EE="$DIR_BUILD_EE/$DIR_DTB_SUFFIX"

echo 'Copying device-trees...'
cp -ra "$DIR_DTB_CE" "$DIR_PART1/ce_device_trees" || die 'Failed to copy CE dtb'
cp -ra "$DIR_DTB_EE" "$DIR_PART1/ee_device_trees" || die 'Failed to copy EE dtb'

build.CoreELEC-Amlogic-ng.arm-20/build/linux-bd0e10d11657ee4771b68dddcbc1948827829818/arch/arm64/boot/Image.lzo

echo 'Copying kernel images...'
cp -a "$DIR_BUILD_CE/build/linux-"*'/arch/arm64/boot/Image.lzo' "$DIR_PART1/ce_kernel.img" || die 'Failed to copy CE kernel'
cp -a "$DIR_BUILD_EE/build/linux-"*'/arch/arm64/boot/Image.lzo' "$DIR_PART1/ee_kernel.img" || die 'Failed to copy CE kernel'

echo 'Copying system images...'
cp -a "$DIR_BUILD_CE/image/system" "$DIR_SYSTEM/coreelec"
cp -a "$DIR_BUILD_EE/image/system" "$DIR_SYSTEM/emuelec"

echo 'Creating system img...'
fakeroot mksquashfs "$DIR_SYSTEM" "$DIR_PART1/SYSTEM" -noappend -comp lzo -Xcompression-level 9 -b 524288

echo 'Creating md5sums...'
for FILE in "$DIR_PART1/"{ce_kernel.img,ee_kernel.img,SYSTEM}; do
    md5sum "$FILE" > "$FILE.md5" || die "Failed to calculate md5sum of '$FILE'"
done

echo 'Mcopying files into system partition..'
mcopy -i "$IMAGE_PART1" "$DIR_SYSTEM"/* :: || die 'Failed to populate the system partition'
echo 'Checking if fat32 on system partition is ok...'
fsck.vfat -an "$IMAGE_PART1" || die 'Failed to fsck the system partition'

echo 'Merging partitions into whole image...'
dd if="$IMAGE_PART1" of="$IMAGE_DISK" bs=1M seek=1 || die 'Failed to write system partition into whole image'
dd if="$IMAGE_PART2" of="$IMAGE_DISK" bs=1M seek=2049 || die 'Failed to write storage partition into whole image'

echo 'Compressing image...'
pigz -9v "$IMAGE_DISK" || die 'Failed to compress image'

echo 'Everything done'